### PR TITLE
Add line chart to landing currency

### LINKED ISSUE #73: Add line chart to landing currency
Add a Plotly line chart to the LandingCurrency component that will be displayed when it is expanded. This line chart will display price over time for a cryptocurrency.

### PR DESCRIPTION
**Pull request by zingsurfer**
# closes #73 

- [ ] Wrote Tests
- [X] Implemented
- [X] Reviewed

# Necessary checkmarks:

- [ ] All Tests are Passing - not all, but more are passing now

- [X] The code will run locally

## Type of change

- [X] New feature
- [X] Resolve test errors

# Description:
# New feature:
Adds a Plotly line chart to the LandingCurrency component that is displayed when it is expanded. This line chart displays price over time for a Bitcoin, but the next goal would be to make this dynamic for whatever coin. I or someone else can work on that on a separate branch. 

# Resolve test errors: 
I followed advice [here](https://github.com/plotly/react-plotly.js/issues/115) to resolve the error I saw when I ran the Jest test suite: window.URL.createObjectURL is not a function. To fix it, I added `window.URL.createObjectURL = function() {};` to `src/setupTests.js`.
 
# Check the correct boxes

- [X] This broke nothing
- [ ] This broke some stuff
- [ ] This broke everything

# Testing Changes

- [X] No Tests have been changed
- [ ] Tests have been added
- [ ] Some Tests have been changed
- [ ] All of the Tests have been changed(Please describe what in the world happened)

# Checklist:

- [X] My code has no commented out code (explanatory comments are fine)
- [X] I have reviewed my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have fully tested my code

# Progress pic: 
screen shot 2019-01-18

# Please Include a link to a gif of your feelings about this branch

### CODE REVIEW

**Comment by zingsurfer** [comment]
@djcaraballo @30ozSteak @DanielMulitauopele please let me know if any one of you could make this dynamic! If not, I may be able to look into it some this evening/tomorrow.

**Comment by djcaraballo** [comment]
Looks great, Autumn! We will probably move it to the expanded component view, but it looks great!

**Comment by zingsurfer** [comment]
Thanks Dina!

**Review by djcaraballo — COMMENTED** [review]
Styling like a front-ender! Good job, Autumn!

**Pull request merged**
